(cl:in-package custom_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          IMU_GYRO_X-VAL
          IMU_GYRO_X
          IMU_GYRO_Y-VAL
          IMU_GYRO_Y
          IMU_GYRO_Z-VAL
          IMU_GYRO_Z
          IMU_GYRO_COMPASS_X-VAL
          IMU_GYRO_COMPASS_X
          IMU_GYRO_COMPASS_Y-VAL
          IMU_GYRO_COMPASS_Y
          IMU_GYRO_COMPASS_Z-VAL
          IMU_GYRO_COMPASS_Z
          Q1-VAL
          Q1
          Q2-VAL
          Q2
          Q3-VAL
          Q3
          Q4-VAL
          Q4
          ROLLSPEED-VAL
          ROLLSPEED
          PITCHSPEED-VAL
          PITCHSPEED
          YAWSPEED-VAL
          YAWSPEED
          INTERNAL_PRESSURE-VAL
          INTERNAL_PRESSURE
          EXTERNAL_PRESSURE-VAL
          EXTERNAL_PRESSURE
          HEADING-VAL
          HEADING
))